Update unit_test_mysql57.yml

diff --git a/.github/workflows/unit_test_mysql57.yml b/.github/workflows/unit_test_mysql57.yml
--- a/.github/workflows/unit_test_mysql57.yml
+++ b/.github/workflows/unit_test_mysql57.yml
@@ -78,3 +78,45 @@ jobs:
       timeout-minutes: 30
       run: |
         eatmydata -- make unit_test
+        
+  armv64_job:
+      name: Build and Test for arm64
+      runs-on: ubuntu-18.04
+      
+      env:
+        GOTEST: gotestsum --
+      steps:
+        - uses: actions/setup-go@v2
+          with:
+            go-version: '1.18.2'
+        - uses: actions/checkout@v2
+        
+        - name: Set up QEMU
+          id: qemu
+          uses: docker/setup-qemu-action@v1
+        - name: Install and Run tests
+          run: |
+            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
+              arm64v8/ubuntu:18.04 \
+              bash -exc 'apt-get update  && \
+              apt-get install -y sudo && \
+              sudo apt-get install -y golang-go && \
+              echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range && \
+              echo "fs.aio-max-nr = 1048576" | sudo tee -a /etc/sysctl.conf && \
+              sudo sysctl -p /etc/sysctl.conf && \
+              export DEBIAN_FRONTEND="noninteractive" && \
+              sudo apt-get update && \
+              sudo apt-get install -y mysql-server mysql-client && \
+              sudo apt-get install -y make unzip g++ curl git wget ant openjdk-8-jdk eatmydata && \
+              sudo service mysql stop && \
+              sudo bash -c "echo '/usr/sbin/mysqld { }' > /etc/apparmor.d/usr.sbin.mysqld" # https://bugs.launchpad.net/ubuntu/+source/mariadb-10.1/+bug/1806263 && \
+              sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/ && \
+              sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld || echo "could not remove mysqld profile" && \
+              mkdir -p dist bin && \
+              curl -L https://github.com/coreos/etcd/releases/download/v3.3.10/etcd-v3.3.10-linux-amd64.tar.gz | tar -zxC dist && \
+              mv dist/etcd-v3.3.10-linux-amd64/{etcd,etcdctl} bin/ && \
+              go mod download && \
+              go install golang.org/x/tools/cmd/goimports@latest && \
+              make tools && \
+              eatmydata -- make unit_test'
+ 
